// Code generated by MockGen. DO NOT EDIT.
// Source: loan.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/mamtaharris/mini-aspire/internal/models/entities"
)

// MockLoanRepo is a mock of LoanRepo interface.
type MockLoanRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLoanRepoMockRecorder
}

// MockLoanRepoMockRecorder is the mock recorder for MockLoanRepo.
type MockLoanRepoMockRecorder struct {
	mock *MockLoanRepo
}

// NewMockLoanRepo creates a new mock instance.
func NewMockLoanRepo(ctrl *gomock.Controller) *MockLoanRepo {
	mock := &MockLoanRepo{ctrl: ctrl}
	mock.recorder = &MockLoanRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoanRepo) EXPECT() *MockLoanRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLoanRepo) Create(ctx context.Context, loan entities.Loans) (entities.Loans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, loan)
	ret0, _ := ret[0].(entities.Loans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLoanRepoMockRecorder) Create(ctx, loan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLoanRepo)(nil).Create), ctx, loan)
}

// GetByID mocks base method.
func (m *MockLoanRepo) GetByID(ctx context.Context, loanID int) (entities.Loans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, loanID)
	ret0, _ := ret[0].(entities.Loans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLoanRepoMockRecorder) GetByID(ctx, loanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLoanRepo)(nil).GetByID), ctx, loanID)
}

// Update mocks base method.
func (m *MockLoanRepo) Update(ctx context.Context, loan entities.Loans) (entities.Loans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, loan)
	ret0, _ := ret[0].(entities.Loans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockLoanRepoMockRecorder) Update(ctx, loan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoanRepo)(nil).Update), ctx, loan)
}
